<a href="https://colab.research.google.com/github/Prince736802/Navbar/blob/main/universal%20Bank%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd

In [34]:
default = pd.read_csv('/content/UniversalBank.csv')

In [35]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [36]:
default.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,PersonalLoan,SecuritiesAccount,CDAccount,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [37]:
default.isnull().sum()

ID                   0
Age                  0
Experience           0
Income               0
ZIP Code             0
Family               0
CCAvg                0
Education            0
Mortgage             0
PersonalLoan         0
SecuritiesAccount    0
CDAccount            0
Online               0
CreditCard           0
dtype: int64

In [38]:
default.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 5000 non-null   int64
 1   Age                5000 non-null   int64
 2   Experience         5000 non-null   int64
 3   Income             5000 non-null   int64
 4   ZIP Code           5000 non-null   int64
 5   Family             5000 non-null   int64
 6   CCAvg              5000 non-null   float64
 7   Education          5000 non-null   int64
 8   Mortgage           5000 non-null   int64
 9   PersonalLoan       5000 non-null   int64
 10  SecuritiesAccount  5000 non-null   int64
 11  CDAccount          5000 non-null   int64
 12  Online             5000 non-null   int64
 13  CreditCard         5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB

In [39]:
default.describe()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,PersonalLoan,SecuritiesAccount,CDAccount,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,93152.503000,2.396400,1.937938,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852197,1.147663,1.747659,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [40]:
default['PersonalLoan'].value_counts()

PersonalLoan
0    4520
1     480
Name: count, dtype: int64

In [41]:
default.columns

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'PersonalLoan', 'SecuritiesAccount',
       'CDAccount', 'Online', 'CreditCard'],
      dtype='object')

In [42]:
y = default['PersonalLoan']

In [43]:
X = default.drop(['PersonalLoan'],axis=1)

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=3000)

In [45]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3500, 13), (1500, 13), (3500,), (1500,))

In [46]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [47]:
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [48]:
model.intercept_

array([-4.41750165e-05])

In [49]:
model.coef_

array([[-1.81120368e-05,  6.87796664e-03,  6.23684380e-03,
         3.59172618e-02, -6.90827557e-05,  7.11846163e-03,
         3.90333973e-03,  8.90522882e-03,  8.70875325e-04,
         3.92625829e-04,  2.52118577e-03, -1.38947266e-04,
         1.18647228e-04]])

In [50]:
y_pred = model.predict(X_test)

In [51]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [53]:
confusion_matrix(y_test,y_pred)

array([[1318,   44],
       [  84,   54]])

In [54]:
accuracy_score(y_test,y_pred)

0.9146666666666666

In [55]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.97      0.95      1362
           1       0.55      0.39      0.46       138

    accuracy                           0.91      1500
   macro avg       0.75      0.68      0.71      1500
weighted avg       0.90      0.91      0.91      1500

In [56]:
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
print('\nAccuracy Score:')
print(accuracy_score(y_test, y_pred))
print('\nClassification Report:')
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[1318   44]
 [  84   54]]

Accuracy Score:
0.9146666666666666

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.97      0.95      1362
           1       0.55      0.39      0.46       138

    accuracy                           0.91      1500
   macro avg       0.75      0.68      0.71      1500
weighted avg       0.90      0.91      0.91      1500